spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
    username: sa
    password: password

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true


logging:
  level:
    ru.yandex.practicum.filmorate: TRACE
  file:
    name: ${LOGGING_FILE_PATH}  # Путь к файлу для логов