spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    ru.yandex.practicum.filmorate: TRACE