spring:
  datasource:
    url: jdbc:postgresql://filmorate-postgres:5432/filmsdb
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

logging:
  level:
    ru.yandex.practicum.filmorate: TRACE